[phases.setup]
nixPkgs = [
  "python312Full",
  "gcc",
  "libnss3",
  "atk",
  "cups",
  "pango",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libxkbcommon",
  "libx11",
  "libxext",
  "libxfixes",
  "libxcb",
  "libxrender",
  "gtk3",
  "mesa",
  "alsa-lib"
]

